name: Deploy to production
on:
  push:
    branches:
      - "production"

jobs:
  redeploy_everything:
    name: Deploying everything to production
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and Restart Services
        uses: appleboy/ssh-action@v1
        with:
          host: 11.11.11.11
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            cd monorepo_ci_cd_cert
            git_pull
            pnpm install
            pnpm run build
            pm2 restart http-backend
            pm2 restart ws-backend
            pm2 restart frontend
